sudo:
  false

language:
  php

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 library/
  - vendor/bin/phpmd library/ text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpunit

notifications:
  email: false
